dubbo.zk.address: 218.244.135.116:2181
dubbo.zk.session.timeout: 180000
dubbo.zk.connect.timeout: 30000
dubbo.protocol.port: 2881
dubbo.version: 1.0.0.daily


spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.106.196:3306/practice-mybatis?characterEncoding=utf8&useSSL=false&statementInterceptors=com.sxc.dubbo.mysql.TraceStatemengInterceptor
    username: root
    password: 123456

