spring:
  application:
    name: practice-mybaits
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.106.196:3306/practice-mybatis?characterEncoding=utf8
    password: 123456
    username: root

#mybatis
mybatis:
  type-aliases-package: com.sxc.tk.mybatis.orm
  mapper-locations: classpath:mapper/*.xml

#mapper
mapper:
  mappers: com.sxc.tk.mybatis.mapper.MyMapper
  not-empty: false
  identity: mysql